### ISSUE TITLE
Add support for Ollama 0.5.1

### ISSUE THREAD

**Issue by dongchen-coder** [SWE-agent/SWE-agent#858]
### Describe the feature

It would be great if this project could add official support for Ollama 0.5.1. Some of the newer models, such as llama-3.3 and llama-3.2, are work well with higher versions of Ollama, and ensuring compatibility with 0.5.1 would allow users to take full advantage of the latest models.

Thank you for considering this feature request!

### Potential Solutions

enhance model.py ?

**Comment by klieret** [comment]
Hi, we use `litellm` for supporting most of our models, do they not support Ollama 0.5.1? See here: https://docs.litellm.ai/docs/providers/ollama . Since they're specializing in model support, I think asking over there would be the easiest way to get support for it in swe-agent as well. Or are you looking for something special?

**Comment by dongchen-coder** [comment]
Thanks for the reply. I will switch to `litellm` then.
